name: your_app_name
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: ^3.0.0

# ----------------------------
# ğŸ“¦ Dependencies
# ----------------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  dio: ^5.7.0
  connectivity_plus: ^6.0.5
  logger: ^2.4.0
  flutter_native_splash: ^2.4.6
  responsive_framework: ^1.5.1

# ----------------------------
# ğŸ§ª Dev Dependencies
# ----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# ----------------------------
# ğŸ¯ Flutter Configuration
# ----------------------------
flutter:
  uses-material-design: true

  # ----------------------------
  # ğŸ–¼ï¸ Asset folder for images, fonts, etc.
  # ----------------------------
  assets:
    - assets/images/
    - assets/fonts/
    - assets/envs/
